const creatorsData = [
  {
    id: 0,
    name: "Muhammad Awais Razzaq",
    role: "SEO & WP Developer",
    description: "Expert in search engine optimization and WordPress development.",
    image: "https://randomuser.me/api/portraits/men/10.jpg",
    date: "June 15, 2023",
    bio: "Awais has optimized websites for top search rankings, specializing in WordPress development for scalable solutions.",
    skills: ["SEO", "WordPress", "Web Development", "Content Optimization"],
  },
  {
    id: 1,
    name: "Shoaib Zareen",
    role: "Digital Sales & E-commerce",
    description: "Drives online sales through strategic e-commerce solutions.",
    image: "https://randomuser.me/api/portraits/men/20.jpg",
    date: "May 20, 2023",
    bio: "Shoaib excels in building e-commerce platforms that boost conversions and revenue.",
    skills: ["E-commerce", "Digital Sales", "Shopify", "Marketing"],
  },
  {
    id: 2,
    name: "Arsalan Rashid",
    role: "E-Commerce & SaaS Expert",
    description: "Specializes in SaaS products and e-commerce growth.",
    image: "https://randomuser.me/api/portraits/men/30.jpg",
    date: "April 10, 2023",
    bio: "Arsalan has launched multiple SaaS products and scaled e-commerce businesses globally.",
    skills: ["SaaS", "E-commerce", "Product Management", "Growth Hacking"],
  },
  {
    id: 3,
    name: "Muhammad Ahmed",
    role: "SEO & Blogging Specialist",
    description: "Creates content that ranks high and engages audiences.",
    image: "https://randomuser.me/api/portraits/men/40.jpg",
    date: "March 5, 2023",
    bio: "Ahmed’s blogging strategies have driven millions of views for top-tier websites.",
    skills: ["SEO", "Blogging", "Content Writing", "Keyword Research"],
  },
  {
    id: 4,
    name: "M Yasir Khan",
    role: "GoHighLevel Expert",
    description: "Automates marketing funnels with GoHighLevel.",
    image: "https://randomuser.me/api/portraits/men/50.jpg",
    date: "February 15, 2003",
    bio: "Yasir builds efficient marketing and systems using GoHighLevel for businesses.",
    skills: ["GoHighLevel", "Marketing Automation", "CRM", "Funnel Design"],
  },
];

export default creatorsData;