const allProfiles = [
  {
    id: 0,
    name: "Ali Raza",
    role: "Businessman",
    description: "Ali is a seasoned entrepreneur with over 10 years of experience in the textile industry.",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    date: "April 10, 2025",
    bio: "Ali has built multiple successful textile businesses, focusing on sustainable fabrics and innovative designs.",
    skills: ["Entrepreneurship", "Business Strategy", "Supply Chain Management"],
  },
  {
    id: 1,
    name: "Sara Khan",
    role: "Digital Marketer",
    description: "Sara specializes in SEO and content marketing, helping brands grow their online presence.",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    date: "March 22, 2025",
    bio: "Sara has a proven track record of increasing website traffic by 200% through strategic SEO campaigns.",
    skills: ["SEO", "Content Marketing", "Social Media Strategy"],
  },
  {
    id: 2,
    name: "Ahmed Ali",
    role: "Software Engineer",
    description: "Ahmed is a full-stack developer with a passion for building scalable web applications.",
    image: "https://randomuser.me/api/portraits/men/85.jpg",
    date: "February 15, 2025",
    bio: "seasoned entrepreneur with over 10 years of experience in the textile industry.",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    date: "April 10, 2025",
    bio: "Ali has built multiple successful textile businesses, focusing on sustainable fabrics and innovative designs.",
    skills: ["Entrepreneurship", "Business Strategy", "Supply Chain Management"],
  },
  {
    id: 1,
    name: "Sara Khan",
    role: "Digital Marketer",
    description: "Sara specializes in SEO and content marketing, helping brands grow their online presence.",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    date: "March 22, 2025",
    bio: "Sara has a proven track record of increasing website traffic by 200% through strategic SEO campaigns.",
    skills: ["SEO", "Content Marketing", "Social Media Strategy"],
  },
  {
    id: 2,
    name: "Ahmed Ali",
    role: "Software Engineer",
    description: "Ahmed is a full-stack developer with a passion for building scalable web applications.",
    image: "https://randomuser.me/api/portraits/men/85.jpg",
    date: "February 15, 2025",
    bio: "Ahmed has developed over 50 web applications, specializing in React and Node.js ecosystems.",
    skills: ["React", "Node.js", "Database Management"],
  },
  {
    id: 3,
    name: "Hassan Malik",
    role: "Graphic Designer",
    description: "Hassan creates stunning visuals for brands, with expertise in modern design tools.",
    image: "https://randomuser.me/api/portraits/men/45.jpg",
    date: "January 12, 2025",
    bio: "Hassan has worked with global brands to create visually appealing logos and marketing materials.",
    skills: ["Adobe Photoshop", "Illustrator", "UI Design"],
  },
  {
    id: 4,
    name: "Ayesha Noor",
    role: "Content Writer",
    description: "Ayesha crafts engaging stories and content that connect with audiences worldwide.",
    image: "https://randomuser.me/api/portraits/women/65.jpg",
    date: "December 20, 2024",
    bio: "Ayesha’s content has been published in top-tier blogs, driving engagement and conversions.",
    skills: ["Content Writing", "Storytelling", "Copywriting"],
  },
  {
    id: 5,
    name: "Zainab Fatima",
    role: "Data Analyst",
    description: "Zainab excels in analyzing data to drive business decisions with precision.",
    image: "https://randomuser.me/api/portraits/women/22.jpg",
    date: "November 5, 2024",
    bio: "Zainab has helped companies optimize operations using data-driven insights.",
    skills: ["Python", "SQL", "Data Visualization"],
  },
  {
    id: 6,
    name: "Usman Sheikh",
    role: "Product Manager",
    description: "Usman leads product development with a focus on innovation and user experience.",
    image: "https://randomuser.me/api/portraits/men/78.jpg",
    date: "October 30, 2024",
    bio: "Usman has launched multiple successful products in the tech industry.",
    skills: ["Product Management", "Agile", "User Research"],
  },
  {
    id: 7,
    name: "Bilal Ahmed",
    role: "UI/UX Designer",
    description: "Bilal designs intuitive and user-friendly interfaces for web and mobile apps.",
    image: "https://randomuser.me/api/portraits/men/19.jpg",
    date: "September 15, 2024",
    bio: "Bilal’s designs prioritize usability and aesthetics, enhancing user experiences.",
    skills: ["Figma", "Prototyping", "User Testing"],
  },
  {
    id: 8,
    name: "Fatima Shah",
    role: "Marketing Strategist",
    description: "Fatima develops innovative marketing campaigns to boost brand visibility.",
    image: "https://randomuser.me/api/portraits/women/33.jpg",
    date: "August 10, 2024",
    bio: "Fatima has driven successful campaigns for startups and established brands.",
    skills: ["Campaign Management", "Branding", "Analytics"],
  },
  {
    id: 9,
    name: "Omar Khan",
    role: "DevOps Engineer",
    description: "Omar optimizes cloud infrastructure for seamless application deployment.",
    image: "https://randomuser.me/api/portraits/men/62.jpg",
    date: "July 20, 2024",
    bio: "Omar has expertise in AWS and Docker, ensuring high availability systems.",
    skills: ["AWS", "Docker", "CI/CD"],
  },
  {
    id: 10,
    name: "Sana Iqbal",
    role: "Project Manager",
    description: "Sana ensures projects are delivered on time with exceptional quality.",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    date: "June 25, 2024",
    bio: "Sana has managed cross-functional teams for large-scale projects.",
    skills: ["Project Planning", "Team Leadership", "Scrum"],
  },
  {
    id: 11,
    name: "Arif Hussain",
    role: "Web Developer",
    description: "Arif builds responsive and performant websites using modern technologies.",
    image: "https://randomuser.me/api/portraits/men/25.jpg",
    date: "May 30, 2024",
    bio: "Arif specializes in creating fast and secure web applications.",
    skills: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: 12,
    name: "Maha Qureshi",
    role: "SEO Specialist",
    description: "Maha boosts website rankings with cutting-edge SEO strategies.",
    image: "https://randomuser.me/api/portraits/women/48.jpg",
    date: "April 15, 2024",
    bio: "Maha has improved search rankings for numerous e-commerce platforms.",
    skills: ["SEO", "Keyword Research", "Analytics"],
  },
  {
    id: 13,
    name: "Ibrahim Tariq",
    role: "Mobile Developer",
    description: "Ibrahim creates cross-platform mobile apps with a focus on performance.",
    image: "https://randomuser.me/api/portraits/men/37.jpg",
    date: "March 10, 2024",
    bio: "Ibrahim has developed apps used by thousands of users daily.",
    skills: ["React Native", "Flutter", "Mobile Optimization"],
  },
  {
    id: 14,
    name: "Hina Aslam",
    role: "Content Strategist",
    description: "Hina plans content strategies that engage and convert audiences.",
    image: "https://randomuser.me/api/portraits/women/56.jpg",
    date: "February 20, 2024",
    bio: "Hina’s strategies have doubled engagement for multiple brands.",
    skills: ["Content Planning", "Editorial Strategy", "Analytics"],
  },
  {
    id: 15,
    name: "Yousuf Raza",
    role: "Cloud Architect",
    description: "Yousuf designs scalable cloud solutions for enterprise applications.",
    image: "https://randomuser.me/api/portraits/men/91.jpg",
    date: "January 5, 2024",
    bio: "Yousuf has architected cloud systems for Fortune 500 companies.",
    skills: ["Cloud Architecture", "Azure", "Kubernetes"],
  },
  {
    id: 16,
    name: "Amna Khalid",
    role: "Business Analyst",
    description: "Amna bridges the gap between business needs and technical solutions.",
    image: "https://randomuser.me/api/portraits/women/29.jpg",
    date: "December 15, 2023",
    bio: "Amna has streamlined processes for multiple organizations.",
    skills: ["Requirement Analysis", "Stakeholder Management", "BPMN"],
  },
  {
    id: 17,
    name: "Tahir Mehmood",
    role: "Cybersecurity Expert",
    description: "Tahir secures systems against cyber threats with advanced techniques.",
    image: "https://randomuser.me/api/portraits/men/53.jpg",
    date: "November 10, 2023",
    bio: "Tahir has protected critical systems from cyber attacks.",
    skills: ["Cybersecurity", "Penetration Testing", "Encryption"],
  },
  {
    id: 18,
    name: "Rabia Siddiqui",
    role: "Social Media Manager",
    description: "Rabia grows brand presence through strategic social media campaigns.",
    image: "https://randomuser.me/api/portraits/women/71.jpg",
    date: "October 5, 2023",
    bio: "Rabia has grown social media followings by thousands for her clients.",
    skills: ["Social Media Marketing", "Content Creation", "Analytics"],
  },

  {
    id: 19,
    name: "Ali Khan",
    role: "Frontend Developer",
    likes: "1.2K",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    description: "Expert in React and UI design.",
    date: "September 1, 2023",
    bio: "Ali specializes in creating responsive and visually appealing user interfaces with React and modern frontend tools.",
    skills: ["React", "Tailwind CSS", "UI Design", "JavaScript"],
  },
  {
    id: 20,
    name: "Sana Malik",
    role: "UX Designer",
    likes: "934",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    description: "Focused on creating intuitive experiences.",
    date: "August 20, 2023",
    bio: "Sana designs user-friendly interfaces that enhance user experiences, with a focus on usability testing.",
    skills: ["Figma", "User Research", "Prototyping", "Wireframing"],
  },
  {
    id: 21,
    name: "Hamza Noor",
    role: "Backend Engineer",
    likes: "781",
    image: "https://randomuser.me/api/portraits/men/58.jpg",
    description: "Loves building scalable systems.",
    date: "July 15, 2023",
    bio: "Hamza builds robust and scalable backend systems using Node.js and databases like MongoDB.",
    skills: ["Node.js", "MongoDB", "API Development", "Express"],
  },
  {
    id: 22,
    name: "Zoya Ahmed",
    role: "Marketing Manager",
    likes: "1.4K",
    image: "https://randomuser.me/api/portraits/women/32.jpg",
    description: "Drives brand strategies and growth.",
    date: "June 10, 2023",
    bio: "Zoya has led marketing campaigns that significantly boosted brand visibility and revenue.",
    skills: ["Digital Marketing", "Branding", "Campaign Management", "Analytics"],
  },
  {
    id: 23,
    name: "Imran Qureshi",
    role: "DevOps Engineer",
    likes: "623",
    image: "https://randomuser.me/api/portraits/men/44.jpg",
    description: "Streamlines deployments and infra.",
    date: "May 25, 2023",
    bio: "Imran optimizes CI/CD pipelines and cloud infrastructure for seamless deployments.",
    skills: ["AWS", "Docker", "CI/CD", "Kubernetes"],
  },
  {
    id: 24,
    name: "Mehak Tariq",
    role: "Psychologist",
    likes: "842",
    image: "https://randomuser.me/api/portraits/women/26.jpg",
    description: "Helps people build better lives.",
    date: "April 30, 2023",
    bio: "Mehak provides counseling and mental health support, focusing on personal growth.",
    skills: ["Counseling", "Mental Health", "Therapy", "Communication"],
  },
  {
    id: 25,
    name: "Omar Saleem",
    role: "AI Researcher",
    likes: "1.1K",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    description: "Solves problems with AI models.",
    date: "March 15, 2023",
    bio: "Omar develops cutting-edge AI models for real-world problem-solving.",
    skills: ["Machine Learning", "Python", "AI Research", "TensorFlow"],
  },
  {
    id: 26,
    name: "Hiba Rizvi",
    role: "Content Writer",
    likes: "997",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    description: "Writes impactful stories and blogs.",
    date: "February 10, 2023",
    bio: "Hiba creates engaging content that drives audience interaction and brand loyalty.",
    skills: ["Content Writing", "Copywriting", "Storytelling", "SEO"],
  },
  {
    id: 27,
    name: "Faizan Shah",
    role: "Game Developer",
    likes: "765",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    description: "Builds immersive game experiences.",
    date: "January 5, 2023",
    bio: "Faizan develops interactive and immersive games using Unity and C#.",
    skills: ["Unity", "C#", "Game Design", "3D Modeling"],
  },
  {
    id: 28,
    name: "Ayesha Butt",
    role: "Teacher",
    likes: "1.3K",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    description: "Loves sharing knowledge with kids.",
    date: "December 20, 2022",
    bio: "Ayesha is passionate about educating young minds and fostering creativity.",
    skills: ["Teaching", "Curriculum Development", "Child Psychology", "Communication"],
  },
  {
    id: 29,
    name: "Rizwan Mir",
    role: "SEO Expert",
    likes: "890",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    description: "Optimizes online visibility and traffic.",
    date: "November 15, 2022",
    bio: "Rizwan boosts website rankings with advanced SEO techniques and analytics.",
    skills: ["SEO", "Keyword Research", "Google Analytics", "Content Optimization"],
  },
  {
    id: 30,
    name: "Nimra Hashmi",
    role: "HR Manager",
    likes: "688",
    image: "https://randomuser.me/api/portraits/women/80.jpg",
    description: "Connects talent with opportunities.",
    date: "October 10, 2012",
    bio: "Nimra excels in talent acquisition and creating positive workplace cultures.",
    skills: ["Recruitment", "Employee Relations", "HR Strategy", "Training"],
  },
];
export default allProfiles;


