const sliderProfiles = [
  {
    id: 0,
    name: "Ali Raza",
    role: "Businessman",
    description: "Specialist in textile export and brand strategy.",
    image: "public/images/men.jpeg",
    date: "April 10, 2025",
    bio: "Ali is a veteran in the textile industry, leading export initiatives and building global brand strategies.",
    skills: ["Textile Export", "Brand Strategy", "International Business", "Supply Chain"],
  },
  {
    id: 1,
    name: "Sara Khan",
    role: "Teacher",
    description: "Passionate educator in modern learning systems.",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
    date: "March 22, 2025",
    bio: "Sara is dedicated to transforming education through innovative teaching methods and technology.",
    skills: ["Teaching", "EdTech", "Curriculum Design", "Student Engagement"],
  },
  {
    id: 2,
    name: "Ahmed Ali",
    role: "Developer",
    description: "Full-stack developer and system architect.",
    image: "https://images.unsplash.com/photo-1603415526960-f8f10f0b8f3b?auto=format&fit=crop&w=400&q=80",
    date: "Feb 15, 2025",
    bio: "Ahmed designs and builds scalable web applications with expertise in both frontend and backend technologies.",
    skills: ["React", "Node.js", "System Architecture", "Database Management"],
  },
  {
    id: 3,
    name: "Zara Sheikh",
    role: "Designer",
    description: "Creative mind behind top fashion campaigns.",
    image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80",
    date: "May 1, 2025",
    bio: "Zara creates stunning visuals for leading fashion brands, blending creativity with market trends.",
    skills: ["Fashion Design", "Graphic Design", "Creative Direction", "Adobe Suite"],
  },
  {
    id: 4,
    name: "Noman Tariq",
    role: "Marketing Lead",
    description: "Drives revenue through digital campaigns.",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80",
    date: "Jan 19, 2025",
    bio: "Noman spearheads digital marketing campaigns that drive significant revenue growth for businesses.",
    skills: ["Digital Marketing", "Campaign Management", "SEO", "Analytics"],
  },
  {
    id: 5,
    name: "Areeba Qureshi",
    role: "Psychologist",
    description: "Helping people through emotional healing.",
    image: "https://images.unsplash.com/photo-1552058544-f2b08422138a?auto=format&fit=crop&w=400&q=80",
    date: "March 5, 2025",
    bio: "Areeba provides compassionate counseling to support emotional well-being and personal growth.",
    skills: ["Counseling", "Mental Health", "Therapy", "Emotional Intelligence"],
  },
];

export default sliderProfiles;